package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0



/**
 * Banners generated by hbm2java
 */
public class Banners  implements java.io.Serializable {


     private Integer idBanners;
     private String bannername;
     private String lastupdate;
     private Boolean active;

    public Banners() {
    }

    public Banners(String bannername, String lastupdate, Boolean active) {
       this.bannername = bannername;
       this.lastupdate = lastupdate;
       this.active = active;
    }
   
    public Integer getIdBanners() {
        return this.idBanners;
    }
    
    public void setIdBanners(Integer idBanners) {
        this.idBanners = idBanners;
    }
    public String getBannername() {
        return this.bannername;
    }
    
    public void setBannername(String bannername) {
        this.bannername = bannername;
    }
    public String getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(String lastupdate) {
        this.lastupdate = lastupdate;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


