package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cartid;
     private UserReg userReg;
     private Integer productCount;
     private Double totalAmount;
     private Date dateTime;
     private Set cartProductRegs = new HashSet(0);

    public Cart() {
    }

	
    public Cart(UserReg userReg) {
        this.userReg = userReg;
    }
    public Cart(UserReg userReg, Integer productCount, Double totalAmount, Date dateTime, Set cartProductRegs) {
       this.userReg = userReg;
       this.productCount = productCount;
       this.totalAmount = totalAmount;
       this.dateTime = dateTime;
       this.cartProductRegs = cartProductRegs;
    }
   
    public Integer getCartid() {
        return this.cartid;
    }
    
    public void setCartid(Integer cartid) {
        this.cartid = cartid;
    }
    public UserReg getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(UserReg userReg) {
        this.userReg = userReg;
    }
    public Integer getProductCount() {
        return this.productCount;
    }
    
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Set getCartProductRegs() {
        return this.cartProductRegs;
    }
    
    public void setCartProductRegs(Set cartProductRegs) {
        this.cartProductRegs = cartProductRegs;
    }




}


