package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Colour generated by hbm2java
 */
public class Colour  implements java.io.Serializable {


     private Integer idColour;
     private String colour;
     private Set productRegs = new HashSet(0);

    public Colour() {
    }

    public Colour(String colour, Set productRegs) {
       this.colour = colour;
       this.productRegs = productRegs;
    }
   
    public Integer getIdColour() {
        return this.idColour;
    }
    
    public void setIdColour(Integer idColour) {
        this.idColour = idColour;
    }
    public String getColour() {
        return this.colour;
    }
    
    public void setColour(String colour) {
        this.colour = colour;
    }
    public Set getProductRegs() {
        return this.productRegs;
    }
    
    public void setProductRegs(Set productRegs) {
        this.productRegs = productRegs;
    }




}


