package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0



/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer commentid;
     private UserReg userReg;
     private String comment;

    public Comment() {
    }

	
    public Comment(UserReg userReg) {
        this.userReg = userReg;
    }
    public Comment(UserReg userReg, String comment) {
       this.userReg = userReg;
       this.comment = comment;
    }
   
    public Integer getCommentid() {
        return this.commentid;
    }
    
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }
    public UserReg getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(UserReg userReg) {
        this.userReg = userReg;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


