package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer iddelivery;
     private UserReg userReg;
     private String address1;
     private String address2;
     private String town;
     private String city;
     private Date dateTime;

    public Delivery() {
    }

	
    public Delivery(UserReg userReg) {
        this.userReg = userReg;
    }
    public Delivery(UserReg userReg, String address1, String address2, String town, String city, Date dateTime) {
       this.userReg = userReg;
       this.address1 = address1;
       this.address2 = address2;
       this.town = town;
       this.city = city;
       this.dateTime = dateTime;
    }
   
    public Integer getIddelivery() {
        return this.iddelivery;
    }
    
    public void setIddelivery(Integer iddelivery) {
        this.iddelivery = iddelivery;
    }
    public UserReg getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(UserReg userReg) {
        this.userReg = userReg;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


