package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Interfaces generated by hbm2java
 */
public class Interfaces  implements java.io.Serializable {


     private Integer idinterfaces;
     private String url;
     private String displayName;
     private Set privilageses = new HashSet(0);

    public Interfaces() {
    }

    public Interfaces(String url, String displayName, Set privilageses) {
       this.url = url;
       this.displayName = displayName;
       this.privilageses = privilageses;
    }
   
    public Integer getIdinterfaces() {
        return this.idinterfaces;
    }
    
    public void setIdinterfaces(Integer idinterfaces) {
        this.idinterfaces = idinterfaces;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Set getPrivilageses() {
        return this.privilageses;
    }
    
    public void setPrivilageses(Set privilageses) {
        this.privilageses = privilageses;
    }




}


