package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * LoginSessions generated by hbm2java
 */
public class LoginSessions  implements java.io.Serializable {


     private Integer idloginSessions;
     private UserReg userReg;
     private String ipAddress;
     private Date inTime;
     private Date outTime;

    public LoginSessions() {
    }

	
    public LoginSessions(UserReg userReg) {
        this.userReg = userReg;
    }
    public LoginSessions(UserReg userReg, String ipAddress, Date inTime, Date outTime) {
       this.userReg = userReg;
       this.ipAddress = ipAddress;
       this.inTime = inTime;
       this.outTime = outTime;
    }
   
    public Integer getIdloginSessions() {
        return this.idloginSessions;
    }
    
    public void setIdloginSessions(Integer idloginSessions) {
        this.idloginSessions = idloginSessions;
    }
    public UserReg getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(UserReg userReg) {
        this.userReg = userReg;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Date getInTime() {
        return this.inTime;
    }
    
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }




}


