package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Memory generated by hbm2java
 */
public class Memory  implements java.io.Serializable {


     private Integer idMemory;
     private String mem;
     private Set productRegs = new HashSet(0);

    public Memory() {
    }

    public Memory(String mem, Set productRegs) {
       this.mem = mem;
       this.productRegs = productRegs;
    }
   
    public Integer getIdMemory() {
        return this.idMemory;
    }
    
    public void setIdMemory(Integer idMemory) {
        this.idMemory = idMemory;
    }
    public String getMem() {
        return this.mem;
    }
    
    public void setMem(String mem) {
        this.mem = mem;
    }
    public Set getProductRegs() {
        return this.productRegs;
    }
    
    public void setProductRegs(Set productRegs) {
        this.productRegs = productRegs;
    }




}


