package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0



/**
 * Privilages generated by hbm2java
 */
public class Privilages  implements java.io.Serializable {


     private Integer privilageid;
     private Interfaces interfaces;
     private UserType userType;

    public Privilages() {
    }

    public Privilages(Interfaces interfaces, UserType userType) {
       this.interfaces = interfaces;
       this.userType = userType;
    }
   
    public Integer getPrivilageid() {
        return this.privilageid;
    }
    
    public void setPrivilageid(Integer privilageid) {
        this.privilageid = privilageid;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }




}


