package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ProductReg generated by hbm2java
 */
public class ProductReg  implements java.io.Serializable {


     private Integer productid;
     private Brand brand;
     private Os os;
     private Colour colour;
     private Memory memory;
     private String productname;
     private Double price;
     private Integer quantity;
     private String productimage;
     private String sim;
     private String announced;
     private String dispalysize;
     private String frontcamera;
     private String seconderycamera;
     private String video;
     private Integer status;
     private Set cartProductRegs = new HashSet(0);

    public ProductReg() {
    }

	
    public ProductReg(Brand brand, Os os, Colour colour, Memory memory) {
        this.brand = brand;
        this.os = os;
        this.colour = colour;
        this.memory = memory;
    }
    public ProductReg(Brand brand, Os os, Colour colour, Memory memory, String productname, Double price, Integer quantity, String productimage, String sim, String announced, String dispalysize, String frontcamera, String seconderycamera, String video, Integer status, Set cartProductRegs) {
       this.brand = brand;
       this.os = os;
       this.colour = colour;
       this.memory = memory;
       this.productname = productname;
       this.price = price;
       this.quantity = quantity;
       this.productimage = productimage;
       this.sim = sim;
       this.announced = announced;
       this.dispalysize = dispalysize;
       this.frontcamera = frontcamera;
       this.seconderycamera = seconderycamera;
       this.video = video;
       this.status = status;
       this.cartProductRegs = cartProductRegs;
    }
   
    public Integer getProductid() {
        return this.productid;
    }
    
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Os getOs() {
        return this.os;
    }
    
    public void setOs(Os os) {
        this.os = os;
    }
    public Colour getColour() {
        return this.colour;
    }
    
    public void setColour(Colour colour) {
        this.colour = colour;
    }
    public Memory getMemory() {
        return this.memory;
    }
    
    public void setMemory(Memory memory) {
        this.memory = memory;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getProductimage() {
        return this.productimage;
    }
    
    public void setProductimage(String productimage) {
        this.productimage = productimage;
    }
    public String getSim() {
        return this.sim;
    }
    
    public void setSim(String sim) {
        this.sim = sim;
    }
    public String getAnnounced() {
        return this.announced;
    }
    
    public void setAnnounced(String announced) {
        this.announced = announced;
    }
    public String getDispalysize() {
        return this.dispalysize;
    }
    
    public void setDispalysize(String dispalysize) {
        this.dispalysize = dispalysize;
    }
    public String getFrontcamera() {
        return this.frontcamera;
    }
    
    public void setFrontcamera(String frontcamera) {
        this.frontcamera = frontcamera;
    }
    public String getSeconderycamera() {
        return this.seconderycamera;
    }
    
    public void setSeconderycamera(String seconderycamera) {
        this.seconderycamera = seconderycamera;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCartProductRegs() {
        return this.cartProductRegs;
    }
    
    public void setCartProductRegs(Set cartProductRegs) {
        this.cartProductRegs = cartProductRegs;
    }




}


