package DB;
// Generated Aug 19, 2015 2:29:07 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserReg generated by hbm2java
 */
public class UserReg  implements java.io.Serializable {


     private Integer idUser;
     private UserType userType;
     private String username;
     private String country;
     private String email;
     private String password;
     private String conPassword;
     private Integer status;
     private Set comments = new HashSet(0);
     private Set carts = new HashSet(0);
     private Set deliveries = new HashSet(0);
     private Set loginSessionses = new HashSet(0);

    public UserReg() {
    }

	
    public UserReg(UserType userType) {
        this.userType = userType;
    }
    public UserReg(UserType userType, String username, String country, String email, String password, String conPassword, Integer status, Set comments, Set carts, Set deliveries, Set loginSessionses) {
       this.userType = userType;
       this.username = username;
       this.country = country;
       this.email = email;
       this.password = password;
       this.conPassword = conPassword;
       this.status = status;
       this.comments = comments;
       this.carts = carts;
       this.deliveries = deliveries;
       this.loginSessionses = loginSessionses;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getConPassword() {
        return this.conPassword;
    }
    
    public void setConPassword(String conPassword) {
        this.conPassword = conPassword;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getDeliveries() {
        return this.deliveries;
    }
    
    public void setDeliveries(Set deliveries) {
        this.deliveries = deliveries;
    }
    public Set getLoginSessionses() {
        return this.loginSessionses;
    }
    
    public void setLoginSessionses(Set loginSessionses) {
        this.loginSessionses = loginSessionses;
    }




}


